server:
  port: 9443
  ssl:
    enabled: true
    key-alias: tmssl
    key-store-password: tomcat123
    key-store: /var/microservices/tmssl.jks
    key-store-type: PKCS12
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"  
      discovery:
        locator:
          enabled: true
      routes:
        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/email/**
        - id: sign-service
          uri: lb://sign-service
          predicates:
            - Path=/sign/**    
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**         
        - id: unidadesMunicipales
          uri: lb://unidadesMunicipales
          predicates:
            - Path=/unidadMunicipal/**
        - id: officers
          uri: lb://officers
          predicates:
            - Path=/officers/**
        - id: participants
          uri: lb://participants
          predicates:
            - Path=/participants/**,/history/**
        - id: prequalifiers
          uri: lb://prequalifiers
          predicates:
            - Path=/prequalifiers/**
        - id: qualification-stages
          uri: lb://qualification-stages
          predicates:
            - Path=/qualificationStages/**,/prequalifications/**,/firstEvaluation/**,/secondEvaluation/**
        - id: qualifications
          uri: lb://qualifications
          predicates:
            - Path=/qualifications/**,/appeals/**,/firstEvaluation/**,/ratifications/**
        - id: qualification-process
          uri: lb://qualification-process
          predicates:
            - Path=/qualifyingBoard/**,/process/**,/sessions/**
        - id: entities-municipal
          uri: lb://entities-municipal
          predicates:
            - Path=/municipal-management/**,/unity-management/**
        - id: users
          uri: lb://users
          predicates:
            - Path=/users/**
        - id: histories-contracting
          uri: lb://histories-contracting
          predicates:
            - Path=/historyContracting/**
        - id: process-service
          uri: lb://process-service
          predicates:
            - Path=/category/**,/document-stage/**,/stages-process/**,/form/**,/bussines-process/**,/process-relations/**,/subCategory/**,/process-signatories/**
        - id: budgets
          uri: lb://budgets
          predicates:
            - Path=/budget/**,/vacancy/**
        - id: contracts-honorary
          uri: lb://contracts-honorary
          predicates:
            - Path=/contractsHonorary/**
        - id: programs-honorary
          uri: lb://programs-honorary
          predicates:
            - Path=/programsHonorary/**,/functions/**
        - id: correlatives-service
          uri: lb://correlatives-service
          predicates:
            - Path=/correlative/**
        - id: applicants
          uri: lb://applicants
          predicates:
            - Path=/applicants/**,/applicantions/**   
        - id: request-recruitment
          uri: lb://request-recruitment
          predicates:
            - Path=/modificationContracts/**,/openPostulations/**,/applicationDefined/**,/renewalContracts/**,/contractRequest/**
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/usersBPM/**
        - id: cases-service
          uri: lb://cases-service
          predicates:
            - Path=/deadline/**,/cases-manager/**,/cases-users/**,/associated-cases/**,/signatories-case/**
        - id: cases-details-service
          uri: lb://cases-details-service
          predicates:
            - Path=/case-document/**,/case-datails/**,/activity-historials/**,/signatories-document/**     
        - id: contracts
          uri: lb://contracts
          predicates:
            - Path=/contracts/**,/templates-contracts/**  
        - id: cas-service
          uri: lb://cas-service
          predicates:
            - Path=/payment-decrees/**   
        - id: document-template-service
          uri: lb://document-template-service
          predicates:
            - Path=/dpd-template/**,/dom-template/**,/rentas-template/**    
        - id: alert-service
          uri: lb://alert-service
          predicates:
            - Path=/alerts/**
        - id: farmacia-service
          uri: lb://farmacia-service
          predicates:
            - Path=/pharmacy-orders/**
        - id: vecinos-service
          uri: lb://vecinos-service
          predicates:
            - Path=/neighbour/**
