server:
  port: 9443
  ssl:
    enabled: true
    key-alias: tmssl
    key-store-password: tomcat123
    key-store: /var/microservices/tmssl.jks
    key-store-type: PKCS12
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"  
      discovery:
        locator:
          enabled: true
      routes:
        - id: farmacia-service
          uri: lb://farmacia-service
          predicates:
            - Path=/pharmacy-orders/**
        - id: vecinos-service
          uri: lb://vecinos-service
          predicates:
            - Path=/neighbour/**
        - id: participants
          uri: lb://participants
          predicates:
            - Path=/participants/**,/history/**
        - id: prequalifiers
          uri: lb://prequalifiers
          predicates:
            - Path=/prequalifiers/**
        - id: qualification-stages
          uri: lb://qualification-stages
          predicates:
            - Path=/qualificationStages/**,/prequalifications/**,/firstEvaluation/**,/secondEvaluation/**,/report-evaluations/**
        - id: qualifications
          uri: lb://qualifications
          predicates:
            - Path=/qualifications/**,/appeals/**,/firstEvaluation/**,/ratifications/**
        - id: qualification-process
          uri: lb://qualification-process
          predicates:
            - Path=/qualifyingBoard/**,/process/**,/sessions/**
        - id: officers
          uri: lb://officers
          predicates:
            - Path=/officers/**
        - id: becas-service
          uri: lb://becas-service
          predicates:
            - Path=/scholarships/**,/scholarshipsManagement/**,/scholarshipsPeriod/**,/scholarshipsType/**,/scholarshipsApplications/**
        - id: entities-municipal
          uri: lb://entities-municipal
          predicates:
            - Path=/municipal-management/**,/unity-management/**
        - id: users
          uri: lb://users
          predicates:
            - Path=/users/**   
        - id: contracts
          uri: lb://contracts
          predicates:
            - Path=/contracts/**,/templates-contracts/**
        - id: request-recruitment
          uri: lb://request-recruitment
          predicates:
            - Path=/modificationContracts/**,/openPostulations/**,/applicationDefined/**,/renewalContracts/**,/contractRequest/**
        - id: applicants
          uri: lb://applicants
          predicates:
            - Path=/applicants/**,/applicantions/**
        - id: budgets
          uri: lb://budgets
          predicates:
            - Path=/budget/**,/vacancy/**
        - id: contracts-honorary
          uri: lb://contracts-honorary
          predicates:
            - Path=/contractsHonorary/**
        - id: programs-honorary
          uri: lb://programs-honorary
          predicates:
            - Path=/programsHonorary/**,/functions/**
        - id: histories-contracting
          uri: lb://histories-contracting
          predicates:
            - Path=/historyContracting/**
        - id: paramether-grales-service
          uri: lb://paramether-grales-service
          predicates:
            - Path=/paramether/bh/**,/paramether/ch/**
        - id: residents-common-service
          uri: lb://residents-common-service
          predicates:
            - Path=/streets/**,/macro-sectors/**,/genders/**,/marital-status/**,/educational-levels/**,/districts/**,/regions/**,/relations/**,/communes/**